# Generated by Django 4.1.7 on 2024-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='python_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('Not_specified', 'NOT_SPECIFIED')], default='Not_specified', max_length=20)),
                ('Qualification', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
