# Generated by Django 4.1.7 on 2024-06-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='python_reg',
        ),
    ]
