# Generated by Django 4.1.7 on 2024-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0002_delete_python_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='python_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(choices=[('python', 'PYTHON'), ('flutter', 'FLUTTER'), ('java', 'JAVA'), ('sql', 'SQL')], max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
    ]
