# Generated by Django 4.1.7 on 2024-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='python_reg',
        ),
    ]
