# Generated by Django 4.1.7 on 2024-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0004_registration_delete_python_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gmail', models.EmailField(max_length=25)),
                ('phoneno', models.IntegerField()),
                ('course', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('payments', models.CharField(max_length=25)),
            ],
        ),
    ]
